### ISSUE TITLE
gets blocked by Instagram for too many login attempts

### ISSUE THREAD

**Issue by MeTaNa-Nima** [5h4d0wb0y/socialbrute#10]
* socialbrute version: latest
* Python version: 2.7/3.8
* Operating System: kali

### Description
i created a new acc, putted real pw in pwlist.
both with --interactive and without it, at first it told cannot do the brute, continue? Yes.
nothing happened,
in interactive i realized it gets blocked by instagram (because of trying many times)

would be great if it used tor or a proxy generator to avoide gettintt,

**Comment by sh4d0wb0y** [comment]
You can try with proxy parameters. Check them on the help!

**Comment by MeTaNa-Nima** [comment]
it only accepts one proxy or a list?

**Comment by sh4d0wb0y** [comment]
One proxy.. Check it on the help menu

**Comment by MeTaNa-Nima** [comment]
so thats a problem, because whats the diffrence? it shall change proxy by every 2 or one attempt.
am i wrong?
