### ISSUE TITLE
No module named socialbrute

### ISSUE THREAD

**Issue by zeeebbbrrraaa** [5h4d0wb0y/socialbrute#3]
root@kali:~# socialbrute
Traceback (most recent call last):                                        File "/usr/local/bin/socialbrute", line 5, in <module>
    from socialbrute.cli import main
  File "/usr/local/lib/python2.7/dist-packages/socialbrute/cli.py", line 10, in <module>
    from socialbrute.socialbrute import *
ImportError: No module named socialbrute

**Comment by 5h4d0wb0y** [comment]
What version of socialbrute and operating system are you using?

**Comment by zeeebbbrrraaa** [comment]
I use socialbrute new version and i use in kalinethunter

**Comment by 5h4d0wb0y** [comment]
Try to use python 3.x launching pip3 install socialbrute --upgrade

**Comment by zeeebbbrrraaa** [comment]
Last login: Sun Oct 27 12:34:56 UTC 2019 on pts/5
Linux kali 3.18.31-perf-ga8bf568 #1 SMP PREEMPT Tue Jul 9 11:22:23 WIB 2019 aarch64

The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@kali:~# pip3 install socialbrute
Collecting socialbrute
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/87/2f/94166f431a30f63e801a01e0188805648d2368f1264b976396e6832562fa/socialbrute-1.0.1-py2.py3-none-any.whl
Collecting terminaltables>=3.1.0 (from socialbrute)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz
Collecting yaspin>=0.14.0 (from socialbrute)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/01/24/27521d29ce5a511c0e4db2a8dea4f888ffd11709bee1878b2e2faa1087e4/yaspin-0.15.0-py2.py3-none-any.whl
Requirement already satisfied: Click>=6.0 in /usr/lib/python3/dist-packages (from socialbrute) (7.0)
Requirement already satisfied: selenium>=3.141.0 in /usr/local/lib/python3.7/dist-packages (from socialbrute) (3.141.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium>=3.141.0->socialbrute) (1.24.1)
Building wheels for collected packages: terminaltables
  Running setup.py bdist_wheel for terminaltables ... done
  Stored in directory: /root/.cache/pip/wheels/30/6b/50/6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
Successfully built terminaltables
Installing collected packages: terminaltables, yaspin, socialbrute
Successfully installed socialbrute-1.0.1 terminaltables-3.1.0 yaspin-0.15.0
root@kali:~# pip3 install socialbrute --upgrade
Requirement already up-to-date: socialbrute in /usr/local/lib/python3.7/dist-packages (1.0.1)
Requirement already satisfied, skipping upgrade: Click>=6.0 in /usr/lib/python3/dist-packages (from socialbrute) (7.0)
Requirement already satisfied, skipping upgrade: yaspin>=0.14.0 in /usr/root@kali:~# socialbrute
Traceback (most recent call last):                                        File "/usr/local/bin/socialbrute", line 10, in <module>
    sys.exit(main())                                                      File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__                                                                        return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)                        File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)                                    TypeError: main() missing 1 required positional argument: 'token'
root@kali:~#

**Comment by zeeebbbrrraaa** [comment]
root@kali:~# socialbrute
Traceback (most recent call last):                                        File "/usr/local/bin/socialbrute", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: main() missing 1 required positional argument: 'token'
root@kali:~#

**Comment by 5h4d0wb0y** [comment]
Problem solved with the new release.
