### ISSUE TITLE
Just says success for first password in list 

### ISSUE THREAD

**Issue by s0up1** [5h4d0wb0y/socialbrute#8]
Was trying to crack a twitter...

Command:
'socialbrute -s twitter -u ******* -w pass.txt'

Output:
✔ Brute forcing... Please wait...
✔ Account cracked!
Username: *******
Password: 123456

Does this for any account I input?

**Comment by sh4d0wb0y** [comment]
I solved this problem on the commit https://github.com/5h4d0wb0y/socialbrute/commit/136c614c38ae6027ecd640dba8440e4b62e11998. Try now the new release!
